### ISSUE TITLE
Error docker run from Dockerfile

### ISSUE THREAD

**Issue by pablorcruh** [jleetutorial/dockerapp#20]
I have an error running docker container, i don't have much experience using Docker and redis that is why i open this issue to ask for help 

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 464, in _connect
    socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 439, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 464, in _connect
    socket.SOCK_STREAM):
  File "/usr/local/lib/python3.5/socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 7, in <module>
    cache.set(default_key, "one")
  File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 1072, in set
    return self.execute_command('SET', *pieces)
  File "/usr/local/lib/python3.5/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python3.5/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.

**Comment by pablorcruh** [comment]
This error is because we need to link the container running the app with a redis container

**Comment by awsdevopro** [comment]
![screenshot from 2017-11-08 14-31-13](https://user-images.githubusercontent.com/32731769/32541528-1d7a0278-c49a-11e7-8be8-0aaa59b128ea.png)
![screenshot from 2017-11-08 15-21-50](https://user-images.githubusercontent.com/32731769/32541539-24ad973a-c49a-11e7-883a-abf6011075e4.png)

I have attached the screenshots and three files as suggested 

template has
-------------------------------------
<html>
  <head>
    <title>key value lookup service</title>
  </head>
  <body>
    <form method="POST">
      <input type="text" name="key" value={‌{ key }}>
      <input type="text" name="cache_value" value={‌{ cache_value }}>
      <input type="submit" name="submit" value="load">
      <input type="submit" name="submit" value="save">
     </form>
  </body>
</html>

------------------

app.py contains

-----------------------------

from flask import Flask, request, render_template
app = Flask(__name__)
default_key = '1'
cache = {default_key: "one"}

@app.route('/', methods=['GET', 'POST'])
def mainpage():

key = default_key
if 'key' in request.form:
    key = request.form['key']

if request.method == 'POST' and request.form['submit'] == 'save':
cache.set(key, request.form['cache_value'])

cache_value = None;
if cache.get(key):
cache_value = cache.get(key).decode('utf-8')

return render_template('index.html', key=key, cache_value=cache_value)

if __name__ == '__main__':
    app.run(host='0.0.0.0')

------------------

Dockerfile contains

-------------------------------------

FROM python:3.5
RUN pip install Flask==0.11.1
RUN useradd -ms /bin/bash admin
USER admin
COPY app /app
WORKDIR /app
CMD ["python", "app.py"] 

When I go to the browser and hit my localhost which is 192.168.0.101:5000, it says 

 "The Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

What is the solution?

**Comment by Davidrjx** [comment]
@pablorcruh any solution?
